name: github Actions
on: push
jobs:
  terraform-sanity-server:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1
      - name: terraform init
        working-directory: ./Terraform
        run: terraform init
      - name: terraform apply
        working-directory: ./Terraform
        run: terraform apply


# create new instances using terraform or cloudformation?
# ssh into new instances
# clone down specific branch
# start the node server
