name: github Actions
on: push
jobs:
  terraform-sanity-server:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/github_actions'
    steps:
      - name: HashiCorp - Setup Terraform
      - uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1
      - uses: actions/checkout@v3
      - run: cd Terraform
      - run: ls -al
      - run: terraform init
      - run: terraform apply


# create new instances using terraform or cloudformation?
# ssh into new instances
# clone down specific branch
# start the node server
