name: Gitlab Actions
on: push
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo $AWS_ACCESS_KEY_ID
      - run: echo $AWS_SECRET_ACCESS_KEY


# create new instances using terraform or cloudformation?
# ssh into new instances
# clone down specific branch
# start the node server