name: Gitlab Actions
on: push
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - run: cd Terraform
      - run: terraform apply


# create new instances using terraform or cloudformation?
# ssh into new instances
# clone down specific branch
# start the node server